Update handling of SQS Queues
upbound/extensions-migration pull request #44
Opened 2023-11-29 23:00 UTC by stevendborrelli

### Description of your changes

Update SQS Queue handling:

- tags can be handled by default
- fix `redrivePolicy` logic

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

tested with the following manifest:
```
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  labels:
    example.tech/infra-revision: "0.1.131"
    crossplane.io/provider-version: v0.42.0
  name: crossplane-official-provider-test
  namespace:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    region: us-east-1
    delaySeconds: 10
    maximumMessageSize: 262144
    messageRetentionPeriod: 345600
    receiveMessageWaitTimeSeconds: 0
    visibilityTimeout: 30
    sseEnabled: true
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "crossplane-official-provider-test-crossplane-official-provider-test",
        "Statement": [
          {
            "Sid": "BasicSQS",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
              "sqs:DeleteMessage",
              "sqs:SendMessage"
            ],
            "Resource": "arn:aws:sqs:us-east-1:1234567890:crossplane-official-provider-test",
            "Condition": {
              "StringLikeIfExists": {
                "aws:SourceAccount": "1234567890"
              }
            }
          }
        ]
      }
    redrivePolicy:
      deadLetterTargetArnRef:
       name: crossplane-official-provider-test-crossplane-official-provider-test-dlq
      maxReceiveCount: 10
    tags:
      App: crossplane-official-provider-test
      Environment: dev
      Name: crossplane-official-provider-test
      Tier: backend
      VS: sandbox
  providerConfigRef:
    name: awsconfig
```

2023-11-29 23:00 UTC, stevendborrelli commented
@haooliveira84 can you review?

2023-11-30 14:33 UTC, haooliveira84 requested changes
I'll left a change

2023-11-30 15:27 UTC, stevendborrelli commented on converters/provider-aws/sqs/queue.go
>  			"deadLetterTargetArn": source.Spec.ForProvider.RedrivePolicy.DeadLetterTargetARNRef.Name,
Resolved.

2023-11-30 19:34 UTC, haooliveira84 approved these changes
LGTM

2023-12-05 07:38 UTC, sergenyalcin approved these changes
Thanks @stevendborrelli LGTM!

2023-12-05 07:39 UTC, merged